### ISSUE TITLE
Server Binding Update.

### ISSUE THREAD

**Issue by raxele123** [Xeio/IdleCodeRedeemer#13]
They bound us to specific servers. Could you do an update for that? Right now I just keep opening Idle Code Redeemer and clicking "refresh" until I get my server.

**Comment by Xeio** [comment]
Oops, so I had actually fixed something related to this a while back and forgot to actually push a new version to the chrome store. 💀

**Comment by Xeio** [comment]
Get version 1.8.0, it should more reliably swap to the correct server from the chest management page if needed.

**Comment by raxele123** [comment]
Thanks. Its working now.
