### ISSUE TITLE
Why did you remove the part of your extension that opens and buys chests and uses blacksmithing contracts? I prefer it over IdleCombos.

### ISSUE THREAD

**Issue by raxele123** [Xeio/IdleCodeRedeemer#17]
Please add it back.

**Comment by Xeio** [comment]
That's still in the extension in the right-click menu on the button.

**Comment by raxele123** [comment]
Since your August 2nd update the "manage chests" button is gone. At least it is for me. I can still load it manually since I still have the link tho.
