### ISSUE TITLE
Some chests fail to get redeemed

### ISSUE THREAD

**Issue by thinkong** [Xeio/IdleCodeRedeemer#3]
Hi.

It seems like sometimes the addon tries to redeem the codes before updating the instance. This makes the first codes not redeemed. 
Can this be fixed?

**Comment by Xeio** [comment]
It always tries without updating the instance ID first. You should see something like this in the logs if it fails, where it retries after getting a new instance ID:

![image](https://user-images.githubusercontent.com/25418/141043087-c0722aa8-564a-4aad-bde3-202b728de94d.png)

**Comment by thinkong** [comment]
Thank you for your answer.. Maybe it is my browser(Vivaldi) that is making the issues. I'll try and get a log next time

**Comment by Darxide23** [comment]
Something has happened on serverside and I think it might be messing with redemption. IdleCombos is failing to purchase/open all chests as well. What seems to be happening with this addon is that it always fails the first unclaimed chest. I can count the number of codes in the #Combinations Discord channel that I have not redeemed and if, for example, the number is 5 then the addon will always redeem 4. Without fail, I can copy/paste the first unredeemed code into the game and it's always the one that was missed. It has been doing this for the past week or so. In the past, a random code would be missed every now and again, but now it is happening every single time with the first code in each batch. For me at least.

Hope that helps.

**Comment by thinkong** [comment]
Yeah.. I forgot to come back to this.. but it wasn't a browser issue..
I just installed the extension on two seperate browsers and run the one after another.
This will give me all the chests..

**Comment by Xeio** [comment]
I pushed a new version... it should at least in theory be a bit more consistent about error handling. I've never seen it fail to submit codes (even if I try on another browser it submits the 50 most recent and they're all duplicates) so you'll have to let me know.

**Comment by Darxide23** [comment]
At some point would it be possible to include a summary at the end displaying each code and the result? That would make it easier to find when it does fail. I will test out the new version after there are some more codes posted.

Edit: I just tested 1.6.1 as there are 8 codes for me. It immediately gave a red box with the error message "Failed to submit code for unknown reason."

Edit2: Retried and it went fine. This time it said 8 codes redeemed and 8 Electrum Chests. That matches up and I have 8 chests in-game now. In 1.6 it would say 8 codes successfully redeemed and 7 Electrum Chests. This is how I knew it was missing one, and it was always the first unredeemed code in Discord. At some point, would it be possible to add a summary at the end showing each code and what it redeemed for? This way I could more easily identify if it starts missing codes again.

Edit3: Ran again today. 6 codes, 6 chests. The bug of missing the first chest seems to be resolved with v1.6.1. Thanks!

**Comment by Xeio** [comment]
Well, that's better at least. Still curious what the failure is, but loudly failing rather than silently failing is an improvement.

**Comment by Darxide23** [comment]
Got another big red "failed to submit code for unknown reason" but restarting it worked fine again. And it's redeeming all codes still, so it's not missing any. Don't know what the fail message is about, but at least it isn't pretending the code is redeemed when it isn't anymore. This is still better.

But like I mentioned before, something is going on with the servers and how they're handling these external calls. People have been complaining in the scripting channel in the Discord about it for a couple of weeks. I'm just guessing it's something related to that and it isn't the extension's fault.

**Comment by Xeio** [comment]
Finally had this happen to me, apparently sometimes the server just tells you to use a different server:
![image](https://user-images.githubusercontent.com/25418/152616282-f0657393-baf7-4863-a5f5-2f5a4d1b13b3.png)

I'll have to see if I can tweak it to handle this one. Weird thing is the first thing I do is always request from the load balancer which server to use. So it told me to use a server, then that server told me to use a different one. 🤷‍♂️

**Comment by Darxide23** [comment]
That has to be what all the fuss is about, then. Funny thing, since v1.6.1, I haven't had any issues with the extension besides sometimes failing at the start. Just restarting works fine. Buying and opening chests works flawlessly, too. IdleCombos only buys/opens ~50% of the chests you request before it thinks it's done, then it refreshes the inventory to show that it didn't actually finish and you've got to run it several more times.

**Comment by thinkong** [comment]
I like the new changes..
at least I don't need to manually enter an unknown code..
I can just reload the extension and it will to it perfectly!

Thanks!

**Comment by Xeio** [comment]
Pushed hopefully the last update to this one. It should now actually handle the server-switch command and then continue (and retry the failed code) on the new server.
