### ISSUE TITLE
Failed to submit code for unknown reason

### ISSUE THREAD

**Issue by Darxide23** [Xeio/IdleCodeRedeemer#4]
Yep, this one again. So there's a special code for people who played one of CNE's other games that is shutting down soon. It's not available to everybody. It's only available on Steam and I guess only to those who played the other game. I'm on EGS and whenever I run the code redeemer, I just get "Failed to submit code for unknown reason" and it is stuck on this code. No matter how many times I refresh, it tries to redeem that code again and I get this error.

The Discord link to the code in question is: https://discord.com/channels/357247482247380994/358044869685673985/947992113843409016

**Comment by zaepho** [comment]
Same issue, perhaps having the option to skip any code post that you have reacted to already would suffice for this and be flexible for any future instances of a similar occurrence.

**Comment by Xeio** [comment]
Fixed in 1.6.3

**Comment by zaepho** [comment]
Can definitely confirm it works! Thanks for the quick turnaround!
