### ISSUE TITLE
Can't handle single-use codes used by someone else.

### ISSUE THREAD

**Issue by Emmotes** [Xeio/IdleCodeRedeemer#7]
When codes get the `"failure_reason":"someone_already_redeemed_combination"` - it doesn't fail gracefully. It says `Failed to submit code for unknown reason.` and stops.

Someone put a single-use survey code into the Discord and it's now trying that code every time I use the extension - even though it's been deleted from Discord.

Example result from a used code `WV7W-LXP7-NQ29`:
`{"success":true,"failure_reason":"someone_already_redeemed_combination","okay":false,"fail_message":"someone_already_redeemed_combination","actions":[],"processing_time":"0.02025","memory_usage":"4 mb","apc_stats":{"gets":1,"gets_time":"0.00000","sets":0,"sets_time":"0.00000"},"db_stats":{"25":false,"1":false,"26":false}}`

**Comment by Xeio** [comment]
Should be fixed in 1.6.5
